services:
  # MySQL
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=second_spring_todo
    ports:
      - "3307:3306"

  # Java
  app:
    build: .
    ports:
      - "8282:8080"
    depends_on:
      - db
    environment:
      # 本番用（MySQL用）
      - SPRING_PROFILES_ACTIVE=prod
      # ファイルの設定をさらに上書きしてMySQLに繋ぐ
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/second_spring_todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true